language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  target-branch: gh-pages
  local_dir: build
  on:
    branch: main