language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ac300b807322812728aa7af63958554f00ac5c7b
  local_dir: build
  on:
    branch: master